cloud.aws:
  region.static: ap-northeast-1
  stack.auto: false

spring:
  datasource:
    username: ${db.username}
    password: ${db.password}
    url: ${db.url}
    driver-class-name: com.mysql.cj.jdbc.Driver
    data: classpath:schema.sql
  mustache:
    cache: false
  h2:
    console:
      enabled : false
  jpa:
    open-session-in-view: false
    show-sql: true
    properties:
      hibernate:
        format_sql: true
    hibernate:
      ddl-auto: create-drop
