spring:
  devtools:
    restart:
      enabled: true
  mustache:
    cache: false
  h2:
    console:
      enabled : true
  jpa:
    open-session-in-view: false
    show-sql: true
    properties:
      hibernate:
        format_sql: true