spring:
  devtools:
    restart:
      enabled: true
  mustache:
    cache: false
  h2:
    console:
      enabled : false
#  datasource:
#    url: jdbc:postgresql://localhost:5432/testdb
#    username: testuser
#    password: testpass
  jpa:
    open-session-in-view: false
    show-sql: true
    properties:
      hibernate:
        format_sql: true