ifndef::snippets[]
:snippets: ../../../build/generated-snippets
endif::[]
:doctype: book
:icons: font
:source-highlighter: highlightjs
:toc: left
:toclevels: 6
:sectlinks:
:operation-http-request-title: Example Request
:operation-http-response-title: Example Response

[[resources]]
= Rest API Guide

[[resources-members]]
== 회원 관리

[[resources-members-create]]
=== 회원 가입

operation::members-create[snippets='http-request']
operation::members-create[snippets='request-headers']
operation::members-create[snippets='request-fields']

operation::members-create[snippets='http-response']
operation::members-create[snippets='response-headers']
operation::members-create[snippets='response-fields']

[[resources-members-login]]
=== 로그인

operation::members-login[snippets='http-request']
operation::members-login[snippets='request-headers']
operation::members-login[snippets='request-fields']

operation::members-login[snippets='http-response']
operation::members-login[snippets='response-headers']
operation::members-login[snippets='response-fields']

[[resources-members-myInfo]]
=== 회원 정보 조회 (내 정보 조회)

operation::members-myInfo[snippets='http-request']
operation::members-myInfo[snippets='request-headers']

operation::members-myInfo[snippets='http-response']
operation::members-myInfo[snippets='response-headers']
operation::members-myInfo[snippets='response-fields']

[[resources-members-unsubscribe]]
=== 회원 탈퇴

operation::members-unsubscribe[snippets='http-request']
operation::members-unsubscribe[snippets='request-headers']

operation::members-unsubscribe[snippets='http-response']