ifndef::snippets[]
:snippets: ../../../build/generated-snippets
endif::[]
:doctype: book
:icons: font
:source-highlighter: highlightjs
:toc: left
:toclevels: 6
:sectlinks:
:operation-http-request-title: Example Request
:operation-http-response-title: Example Response

[[resources]]
= Rest API Guide

[[resources-members]]
== Members

[[resources-members-create]]
=== Sign-up

operation::members-create[snippets='http-request']
operation::members-create[snippets='request-headers']
operation::members-create[snippets='request-fields']

operation::members-create[snippets='http-response']
operation::members-create[snippets='response-headers']
operation::members-create[snippets='response-fields']

[[resources-members-login]]
=== Login

operation::members-login[snippets='http-request']
operation::members-login[snippets='request-headers']
operation::members-login[snippets='request-fields']

operation::members-login[snippets='http-response']
operation::members-login[snippets='response-headers']
operation::members-login[snippets='response-fields']

[[resources-members-myInfo]]
=== Retrieve member information

operation::members-myInfo[snippets='http-request']
operation::members-myInfo[snippets='request-headers']

operation::members-myInfo[snippets='http-response']
operation::members-myInfo[snippets='response-headers']
operation::members-myInfo[snippets='response-fields']

[[resources-members-update-myInfo]]
=== Update member information

operation::members-update-myInfo[snippets='http-request']
operation::members-update-myInfo[snippets='request-headers']
operation::members-update-myInfo[snippets='request-fields']

operation::members-update-myInfo[snippets='http-response']
operation::members-update-myInfo[snippets='response-headers']
operation::members-update-myInfo[snippets='response-fields']

[[resources-members-unsubscribe]]
=== Unsubscribe

operation::members-unsubscribe[snippets='http-request']
operation::members-unsubscribe[snippets='request-headers']

operation::members-unsubscribe[snippets='http-response']