ifndef::snippets[]
:snippets: ../../../build/generated-snippets
endif::[]
:doctype: book
:icons: font
:source-highlighter: highlightjs
:toc: left
:toclevels: 6
:sectlinks:
:operation-http-request-title: Example Request
:operation-http-response-title: Example Response

[[resources]]
= Rest API Guide for YouTubeRank

[[resources-members]]
== Members

[[resources-members-create]]
=== Sign-up

operation::members-create[snippets='http-request']
operation::members-create[snippets='request-headers']
operation::members-create[snippets='request-fields']

operation::members-create[snippets='http-response']
operation::members-create[snippets='response-headers']
operation::members-create[snippets='response-fields']

[[resources-members-login]]
=== Login

operation::members-login[snippets='http-request']
operation::members-login[snippets='request-headers']
operation::members-login[snippets='request-fields']

operation::members-login[snippets='http-response']
operation::members-login[snippets='response-headers']
operation::members-login[snippets='response-fields']


[[resources-members-myInfo]]
=== Retrieve member information

operation::members-myInfo[snippets='http-request']
operation::members-myInfo[snippets='request-headers']

operation::members-myInfo[snippets='http-response']
operation::members-myInfo[snippets='response-headers']
operation::members-myInfo[snippets='response-fields']

[[resources-members-update-myInfo]]
=== Update member information

operation::members-update-myInfo[snippets='http-request']
operation::members-update-myInfo[snippets='request-headers']
operation::members-update-myInfo[snippets='request-fields']

operation::members-update-myInfo[snippets='http-response']
operation::members-update-myInfo[snippets='response-headers']
operation::members-update-myInfo[snippets='response-fields']

[[resources-members-unsubscribe]]
=== Unsubscribe

operation::members-unsubscribe[snippets='http-request']
operation::members-unsubscribe[snippets='request-headers']

operation::members-unsubscribe[snippets='http-response']


[[resources-keywords]]
== Keywords

[[resources-keywords-add-my-keyword]]
=== Add my keyword

operation::keywords-add-my-keyword[snippets='http-request']
operation::keywords-add-my-keyword[snippets='request-headers']
operation::keywords-add-my-keyword[snippets='request-fields']

operation::keywords-add-my-keyword[snippets='http-response']
operation::keywords-add-my-keyword[snippets='response-headers']
operation::keywords-add-my-keyword[snippets='response-fields']

[[resources-keywords-retrieve-my-keyword]]
=== Retrieve my keyword

operation::keywords-retrieve-my-keyword[snippets='http-request']
operation::keywords-retrieve-my-keyword[snippets='request-headers']

operation::keywords-retrieve-my-keyword[snippets='http-response']
operation::keywords-retrieve-my-keyword[snippets='response-headers']
operation::keywords-retrieve-my-keyword[snippets='response-fields']

[[resources-keywords-retrieve-all-my-keywords]]
=== Retrieve all my keywords

operation::keywords-retrieve-all-my-keywords[snippets='http-request']
operation::keywords-retrieve-all-my-keywords[snippets='request-headers']

operation::keywords-retrieve-all-my-keywords[snippets='http-response']
operation::keywords-retrieve-all-my-keywords[snippets='response-headers']
operation::keywords-retrieve-all-my-keywords[snippets='response-fields']

[[resources-keywords-delete-my-keywords]]
=== Delete my keyword

operation::keywords-delete-my-keyword[snippets='http-request']
operation::keywords-delete-my-keyword[snippets='request-headers']

operation::keywords-delete-my-keyword[snippets='http-response']

[[resources-youtube]]
== YouTube

[[resources-youtube-search]]
=== Search youtube

operation::youtube-search[snippets='http-request']
operation::youtube-search[snippets='request-headers']
operation::youtube-search[snippets='request-parameters']

operation::youtube-search[snippets='http-response']
operation::youtube-search[snippets='response-fields']